name: Release

on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: swaglive/robotframework

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Environment - Login to Github Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Environment - Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Setup Environment - Pull docker layers
      run: |
        parallel docker pull ::: \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.repository.default_branch }} \
        || true

    - name: Build - Docker
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BUILDKIT_INLINE_CACHE=1
        cache-from: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.repository.default_branch }}

  create-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs:
    - build-docker

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Environment - Set variable `check-if-prelease`
      id: check-if-prelease
      uses: actions-ecosystem/action-regex-match@v2
      with:
        text: ${{ github.ref }}
        regex: ^refs\/tags\/v?[0-9]+\.[0-9]+\.[0-9]+\-

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: ${{ steps.check-if-prelease.outputs.match != '' }}
        fail_on_unmatched_files: true
        discussion_category_name: Announcements
